[schemes]
"io.element.desktop" = "Element"
xcdoc = "Xcode"
xcode-ci = "Xcode"
tinkerwell = "Tinkerwell"
element = "Element"
zoomphonecall = "zoom.us"
apple-reference-documentation = "Xcode"
zoomphonesms = "zoom.us"
alfred = "Alfred 5"
bruno = "Bruno"
xcarchive = "Xcode"
abc = "Plexamp"
https = "Vivaldi"
x-xcode-ci-build-report-feedback = "Xcode"
zoomcontactcentercall = "zoom.us"
steamlink = "Steam"
xcode-ci-handler = "Xcode"
mailto = "Mail"
steam = "Steam"
http = "Vivaldi"
doc = "Xcode"
x-swift-package-repository-authentication = "Xcode"
x-xcode-documentation = "Xcode"
xcpref = "Xcode"
xcbot = "Xcode"
xcode = "Xcode"
x-source-tag = "Xcode"
xcdevice = "Xcode"

[types]
"com.apple.default-app.web-browser" = "Vivaldi"
"public.video" = "IINA"
"public.aac-audio" = "Cog"
"public.mp3" = "Cog"
"com.apple.log" = "TextEdit"
"com.apple.default-app.mail-client" = "Mail"
"public.mpeg-4" = "IINA"
"com.apple.logicx.project" = "Logic Pro"
"com.apple.logic.project" = "Logic Pro"
"public.html" = "Vivaldi"
"com.apple.ical.backup-package" = "Calendar"
"com.apple.m4a-audio" = "Cog"
